server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 894488801976-4mrastgt6bvujllssuougml93uolgdvv.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 336940092036721
            client-secret: ffab9933ee8c87450b2bad86e12ff3ee
            scope:
              - email
              - public_profile
          naver:
            client-id: O4Pczy6hqvjsY4DXbP7N
            client-secret: eWQUtBeeWS
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원 정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.
            authorization-uri: https://nid.naver.com/oauth2.0/authorize

